apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-ka
  namespace: user11
spec:
  params:
    - name: url
      type: string
    - name: image
      type: string
  workspaces:
    - name: shared-workspace
    - name: kubeconfig-dir
    - name: manifest-dir
  tasks:
    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
      - name: url
        value: $(params.url)
      - name: subdirectory
        value: ""
      - name: deleteExisting
        value: "true"
    - name: list-directory
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: list-directory
      workspaces:
        - name: directory
          workspace: shared-workspace
    - name: buildah
      runAfter:
        - list-directory
      taskRef:
        kind: Task
        name: buildah
      params:
        - name: IMAGE
          value: $(params.image)
        - name: TLSVERIFY
          value: 'false'
        - name: STORAGE_DRIVER
          value: 'vfs'
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: kubernetes-actions
      runAfter:
        - buildah
      taskRef:
        kind: Task
        name: kubernetes-actions
      params:
        - name: script
          value: |
            #!/bin/bash
            DEPLOYMENT_NAME=laravel-app
            kubectl delete deployment $DEPLOYMENT_NAME
            kubectl create deployment $DEPLOYMENT_NAME --replicas=2 --image=docker.io/janckos/tasks:v7
            echo "----------"
            CURRENT_ALREADY_PODS=$(kubectl get deployments $DEPLOYMENT_NAME | awk 'NR==2{print $4}')
            MINIMAL_AVAILABLE_PODS=2
            COUNTER=1
            while [ $((CURRENT_ALREADY_PODS)) -lt $((MINIMAL_AVAILABLE_PODS)) ]
              do
                echo "waiting for pods"
                CURRENT_ALREADY_PODS=$(kubectl get deployments $DEPLOYMENT_NAME | awk 'NR==2{print $4}')
                COUNTER=$(( $COUNTER + 1 ))
                if [ $COUNTER -gt 300 ]
                then
                  echo "It looks something went wrong with the deployment $DEPLOYMENT_NAME. I can not wait more ..."
                  exit 1
                else
                  sleep 3
                fi
            done;
            kubectl get deployment $DEPLOYMENT_NAME -o wide
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
        - name: manifest-dir
          workspace: manifest-dir