apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-
spec:
  taskRef:
    kind: Task
    name: git-clone
  params:
  - name: url
    value: https://github.com/janckos/k8s
  - name: deleteExisting
    value: "true"
  workspaces:
    - name: output
      #emptyDir: {}
      persistentVolumeClaim:
        claimName: shared-workspace
